---

##
# Install / upgrade SeaweedFS filer meta backup
##

- name: Ensure etc path exists
  file:
    path: "{{ seaweedfs_etc }}"
    recurse: true
    state: directory
    owner: "{{ seaweedfs_user | default('root') }}"
    mode: "700"

- name: Ensure filer path exists
  file:
    path: "{{ seaweedfs_filer_path }}"
    recurse: true
    state: directory
    owner: "{{ seaweedfs_user | default('root') }}"
    mode: "700"

# Use memory if filer.toml file not given
- name: Copy backup-filer.toml
  template:
    src: "{{ seaweedfs_backup_filer_toml }}"
    dest: "{{ seaweedfs_etc }}/{{ seaweedfs_meta_backup_toml }}"
    mode: 0644
  notify:
    - restart seaweedfs-meta-backup.service

- name: Copy seaweedfs-meta-backup.service
  template:
    src: seaweedfs-meta-backup.service.j2
    dest: /etc/systemd/system/seaweedfs-meta-backup.service
    mode: 0444
  notify:
    - restart seaweedfs-meta-backup.service

- name: Enable seaweedfs-meta-backup.service
  systemd:
    name: seaweedfs-meta-backup.service
    enabled: true
    state: started
    daemon_reload: true
