---

##
# Install / upgrade SeaweedFS filer
##

- name: Ensure filer path exists
  file:
    path: "{{ seaweedfs_filer_path }}"
    recurse: true
    state: directory
    owner: "{{ seaweedfs_user | default('root') }}"
    mode: "700"
  tags: seaweedfs

- name: Copy filer.toml
  copy:
    content: "{{ seaweedfs_filer_toml }}"
    dest: "{{ seaweedfs_etc }}/filer.toml"
    mode: 0444
  notify:
    - restart seaweedfs-filer.service
    - wait for seaweedfs-filer.service
  tags: seaweedfs

- name: Copy s3config.json
  template:
    content: "{{ seaweedfs_s3_json }}"
    dest: "{{ seaweedfs_etc }}/s3config.json"
    mode: 0444
  notify:
    - restart seaweedfs-filer.service
    - wait for seaweedfs-filer.service
  when: seaweedfs_s3_json is defined
  tags: seaweedfs

- name: Copy seaweedfs-filer.service
  template:
    src: seaweedfs-filer.service.j2
    dest: /etc/systemd/system/seaweedfs-filer.service
    mode: 0444
  notify:
    - restart seaweedfs-filer.service
    - wait for seaweedfs-filer.service
  tags: seaweedfs

- name: Enable seaweedfs-filer.service
  systemd:
    name: seaweedfs-filer.service
    enabled: true
    state: started
    daemon_reload: true
  tags: seaweedfs
