---

##
# Install / upgrade SeaweedFS master
##

- name: Ensure master path exists
  file:
    path: "{{ seaweedfs_master_path }}"
    recurse: true
    state: directory
    owner: "{{ seaweedfs_user | default('root') }}"
    mode: "700"
  tags: seaweedfs

- name: Copy master.toml
  template:
    src: master.toml.j2
    dest: "{{ seaweedfs_etc }}/master.toml"
    mode: 0444
  notify:
    - restart seaweedfs-master.service
    - wait for seaweedfs-master.service
  tags: seaweedfs

- name: Copy seaweedfs-master.service
  template:
    src: seaweedfs-master.service.j2
    dest: /etc/systemd/system/seaweedfs-master.service
    mode: 0444
  notify:
    - restart seaweedfs-master.service
    - wait for seaweedfs-master.service
  tags: seaweedfs

- name: Enable seaweedfs-master.service
  systemd:
    name: seaweedfs-master.service
    enabled: true
    state: started
    daemon_reload: true
  tags: seaweedfs
