---

##
# Install / upgrade SeaweedFS volume
##

- name: Ensure volume paths exist
  file:
    path: "{{ item.1 }}"
    recurse: true
    state: directory
    owner: "{{ seaweedfs_user | default('root') }}"
    mode: "700"
  with_subelements:
    - "{{ seaweedfs_volume_paths }}"
    - path
  tags: seaweedfs

- name: Copy seaweedfs-volume service files
  template:
    src: seaweedfs-volume.service.j2
    dest: "/etc/systemd/system/seaweedfs-volume-{{ item.tag }}.service"
    mode: 0444
  loop: "{{ seaweedfs_volume_paths }}"
  loop_control:
    index_var: my_idx
  tags: seaweedfs

- name: Enable seaweedfs-volume services
  systemd:
    name: "seaweedfs-volume-{{ item.tag }}.service"
    enabled: true
    state: started
    daemon_reload: true
  loop: "{{ seaweedfs_volume_paths }}"
  tags: seaweedfs

- name: Define service handlers
  set_fact:
    "{{ item.tag }}_service_handlers":
      - restart seaweedfs-volume-{{ item.tag }}.service
      - wait for seaweedfs-volume-{{ item.tag }}.service
  loop: "{{ seaweedfs_volume_paths }}"
  tags: seaweedfs
