---

- name: Define variables
  set_fact:
    is_master: false
    is_volume: false
    is_filer: false
    installed_version: "N/A"
    master_ips: "{{ groups['seaweedfs_masters'] | map('extract', hostvars, ['seaweedfs_master_ip']) | join(':{{ seaweedfs_master_port }},') }}:{{ seaweedfs_master_port }}"
  tags: seaweedfs

- name: Test if master install
  set_fact:
    is_master: true
  when: groups['seaweedfs_masters'] is defined and inventory_hostname in groups['seaweedfs_masters']
  tags: seaweedfs

- name: Test if volume install
  set_fact:
    is_volume: true
  when: groups['seaweedfs_volumes'] is defined and inventory_hostname in groups['seaweedfs_volumes']
  tags: seaweedfs

- name: Test if filer install
  set_fact:
    is_filer: true
  when: groups['seaweedfs_filers'] is defined and inventory_hostname in groups['seaweedfs_filers']
  tags: seaweedfs

- name: Install SeaweedFS common components
  include_tasks: install-common.yml
  tags: seaweedfs

- name: Install SeaweedFS master
  include_tasks: install-master.yml
  when: is_master
  tags: seaweedfs

- name: Install SeaweedFS volume
  include_tasks: install-volume.yml
  when: is_volume
  tags: seaweedfs

- name: Install SeaweedFS filer
  include_tasks: install-filer.yml
  when: is_filer
  tags: seaweedfs

- name: Install SeaweedFS filer meta backup
  include_tasks: install-meta-backup.yml
  when: groups['seaweedfs_meta_backups'] is defined and inventory_hostname in groups['seaweedfs_meta_backups'] and seaweedfs_backup_filer_toml is defined
  tags: seaweedfs

- name: Install Proxmox Storage Plugin
  include_tasks: install-proxmox-plugin.yml
  when: groups['seaweedfs_proxmox'] is defined and inventory_hostname in groups['seaweedfs_proxmox']
  tags: seaweedfs
