---

- name: restart seaweedfs-master.service
  systemd:
    name: seaweedfs-master.service
    state: restarted
    daemon_reload: true
  throttle: 1
  when: groups['seaweedfs_masters'] is defined and inventory_hostname in groups['seaweedfs_masters']

- name: restart seaweedfs-volume.service
  systemd:
    name: seaweedfs-volume.service
    state: restarted
    daemon_reload: true
  throttle: 1
  when: groups['seaweedfs_volumes'] is defined and inventory_hostname in groups['seaweedfs_volumes']

- name: restart seaweedfs-filer.service
  systemd:
    name: seaweedfs-filer.service
    state: restarted
    daemon_reload: true
  throttle: 1
  when: groups['seaweedfs_filers'] is defined and inventory_hostname in groups['seaweedfs_filers']

- name: restart seaweedfs-meta-backup.service
  systemd:
    name: seaweedfs-meta-backup.service
    state: restarted
    daemon_reload: true
  when: groups['seaweedfs_meta_backups'] is defined and inventory_hostname in groups['seaweedfs_meta_backups'] and seaweedfs_backup_filer_toml is defined

- name: restart pvedaemon.service
  systemd:
    name: pvedaemon.service
    state: restarted
    daemon_reload: true

- name: restart pvestatd.service
  systemd:
    name: pvestatd.service
    state: restarted
    daemon_reload: true
