---

- name: restart seaweedfs-master.service
  systemd:
    name: seaweedfs-master.service
    state: restarted
    daemon_reload: true
  throttle: 1

- name: wait for seaweedfs-master.service
  wait_for:
    port: "{{ seaweedfs_master_port | int }}"
    delay: 30
    timeout: 60

- name: restart seaweedfs-volume.service
  systemd:
    name: seaweedfs-volume.service
    state: restarted
    daemon_reload: true
  throttle: 1

- name: wait for seaweedfs-volume.service
  wait_for:
    port: "{{ seaweedfs_volume_port | int }}"
    delay: 5
    timeout: 60

- name: restart seaweedfs-filer.service
  systemd:
    name: seaweedfs-filer.service
    state: restarted
    daemon_reload: true
  throttle: 1

- name: wait for seaweedfs-filer.service
  wait_for:
    port: "{{ seaweedfs_filer_port | int }}"
    delay: 5
    timeout: 60

- name: restart seaweedfs-meta-backup.service
  systemd:
    name: seaweedfs-meta-backup.service
    state: restarted
    daemon_reload: true

- name: restart pvedaemon.service
  systemd:
    name: pvedaemon.service
    state: restarted
    daemon_reload: true

- name: restart pvestatd.service
  systemd:
    name: pvestatd.service
    state: restarted
    daemon_reload: true
